name: build + publish

env:
  PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
  PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

      # Future plans in the works to create tarball from within the caprover/deploy-from-github action.
      
      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            backend/
            frontend/dist/
            captain-definition
          outPath: deploy.tar

#      - name: Publish Docker Image
#        uses: matootie/github-docker@v3.1.0
#        with:
#          accessToken: ${{ github.token }}
#          containerRegistry: true
#          buildArgs: |
#            PUBLIC_SUPABASE_URL=${{ secrets.PUBLIC_SUPABASE_URL }}
#            PUBLIC_SUPABASE_ANON_KEY=${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
      
      - name: Deploy on CapRover
        #uses: caprover/deploy-from-github@v1.1.2
        uses: caprover/deploy-from-github@main
        with:
          server: https://trafficplanner.dev
          app: 'www'
          token: '${{ secrets.APP_TOKEN }}'
          image: 'ghcr.io/jackaida/traffic-planner-dev:latest'
